kit:
  name: "Java 3-tier Starter Kit"
  link: https://github.com/qubell/starter-java-web
  applications:
    - name: Java 3-tier Starter Kit
      manifest: https://raw.github.com/jollyrojer/component-petclinic-main/master/main_app.yml
    - name: MySQL DB component
      manifest: https://raw.github.com/jollyrojer/component-mysql/master/mysql.yml
    - name: Tomcat component
      manifest: https://raw.github.com/jollyrojer/component-tomcat/master/tomcat.yml
    - name: HaProxy component
      manifest: https://raw.github.com/jollyrojer/component-haproxy/master/haproxy.yml
  provider:
    name: "Qubell"
    link: http://qubell.com
  documentation:
    overview: |
      This application requires the following items to be conﬁgured in your environment:
        * Amazon EC2 or Rackspace CloudServers account;
        * Ports 80 and 8080 open on the ﬁrewall.
      Please refer to the Getting Started for step-by-step instructions on how to conﬁgure your environment.
